core/urls.py
from django.urls import path
from core.views import index, test_products_view, home_view, product_list, category_list, category_detail, cart_action, get_cart_items, get_cart_count, cart_view
from core import views

app_name = "core"

urlpatterns = [
    # path("ceva/", views.index), 
    path("", index, name="index"),

    path("products", product_list, name="product-list"),

    path("categories", category_list, name="category-list"),
    path("categories", category_list, name="categories"),  # Adaugă acest URL cu numele "categories"
    path('category/<str:category_id>/', views.category_detail, name='category_detail'),

    path('wishlist/toggle/', views.toggle_wishlist, name='toggle-wishlist'),
    path('wishlist/', views.get_wishlist, name='get-wishlist'), 

    path('cart/items/', get_cart_items, name='get_cart_items'),
    path('cart/count/', get_cart_count, name='get_cart_count'),
    path('cart/', cart_view, name='cart_view'),
    path('cart/action/', cart_action, name='cart_action'),

    path("aaaa/", test_products_view, name='test_products'),
    path("aaa/", home_view, name='home'),
    # Here I'm telling it where to put that =)) beaware of the paths!
]

proiect/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings # it accesses settings.py from upper
from django.conf.urls.static import static

from core.views import index, category_detail, category_list, cart_action, cart_view, get_cart_count, get_cart_items
urlpatterns = [
    path('admin/', admin.site.urls),
    # path("", index)
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),    
    path('', include('core.urls')),
    path('', index, name='index'),
    path('categories/', category_list, name='category_list'),  # Verifică acest nume
    path('category/<str:category_id>/', category_detail, name='category_detail'),
     path('cart/action/', cart_action, name='cart_action'),
    path('cart/items/', get_cart_items, name='get_cart_items'),
    path('cart/count/', get_cart_count, name='get_cart_count'),
    path('cart/', cart_view, name='cart_view'),

]

# all thr static files are stored in teh static directory in root directory

if settings.DEBUG:     
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
# from http.client import HTTPResponse
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q
from core.models import Product, Category, Furnizor, CartOrder, CartOrderItems, ProductImages, ProductReview, Wishlist, Address
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
import json

# Create your views here.

def index(request):
    # return HttpResponse('Hello, world!')
    # return HttpResponse('<h1 style="color:red">Hello, world!</h1>')
    # products = Product.objects.all()
    products = Product.objects.filter(featured=True)

    context = {
        "products": products # is the one from above
    }
    return render(request, 'core/index.html', context)
    # return None

# def product_list(request):
#     # return HttpResponse('Hello, world!')
#     # return HttpResponse('<h1 style="color:red">Hello, world!</h1>')
#     products = Product.objects.all()
#     # products = Product.objects.filter(featured=True)

#     context = {
#         "products": products # is the one from above
#     }
#     return render(request, 'core/product_list.html', context)
#     # return None

def get_filtered_products(request):
    """
    Funcție utilitară pentru a obține produsele filtrate și sortate
    """
    # Inițializăm query-ul de bază
    products_list = Product.objects.all()
    
    # Filtrare după preț
    price_range = request.GET.get('price', None)
    if price_range:
        try:
            max_price = float(price_range)
            products_list = products_list.filter(price__lte=max_price)
        except ValueError:
            pass
    
    # Filtrare după categorie
    category_ids = request.GET.getlist('category')
    if category_ids:
        category_filter = Q()
        for category_id in category_ids:
            try:
                category_filter |= Q(category__id=int(category_id))
            except ValueError:
                pass
        products_list = products_list.filter(category_filter)
    
    # Filtrare după disponibilitate în stoc
    in_stock = request.GET.get('in_stock')
    if in_stock == 'true':
        products_list = products_list.filter(in_stock=True)
    
    # Sortare
    sort_by = request.GET.get('sort', 'default')
    if sort_by == 'price-low':
        products_list = products_list.order_by('price')
    elif sort_by == 'price-high':
        products_list = products_list.order_by('-price')
    elif sort_by == 'newest':
        products_list = products_list.order_by('-date')
    elif sort_by == 'popular':
        products_list = products_list.order_by('-featured', 'title')
    
    return products_list, sort_by, category_ids, price_range, in_stock

# def product_list(request):
#     # Obținem toate categoriile pentru filtre
#     categories = Category.objects.all()
    
#     # Inițializăm query-ul de bază
#     products_list = Product.objects.all()
    
#     # Filtrare după preț
#     price_range = request.GET.get('price', None)
#     if price_range:
#         try:
#             max_price = float(price_range)
#             products_list = products_list.filter(price__lte=max_price)
#         except ValueError:
#             # Ignorăm dacă prețul nu este un număr valid
#             pass
    
#     # Filtrare după categorie
#     category_ids = request.GET.getlist('category')
#     if category_ids:
#         category_filter = Q()
#         for category_id in category_ids:
#             try:
#                 category_filter |= Q(category__id=int(category_id))
#             except ValueError:
#                 # Ignorăm dacă ID-ul nu este un număr valid
#                 pass
#         products_list = products_list.filter(category_filter)
    
#     # Filtrare după disponibilitate în stoc
#     in_stock = request.GET.get('in_stock')
#     if in_stock == 'true':
#         products_list = products_list.filter(in_stock=True)
    
#     # Sortare
#     sort_by = request.GET.get('sort', 'default')
#     if sort_by == 'price-low':
#         products_list = products_list.order_by('price')
#     elif sort_by == 'price-high':
#         products_list = products_list.order_by('-price')
#     elif sort_by == 'newest':
#         products_list = products_list.order_by('-date')
#     elif sort_by == 'popular':
#         # Produsele populare sunt cele marcate ca "featured"
#         products_list = products_list.order_by('-featured', 'title')
    
#     # Paginare - 9 produse per pagină
#     paginator = Paginator(products_list, 9)
#     page = request.GET.get('page', 1)
    
#     try:
#         products = paginator.page(page)
#     except:
#         # În caz de erori, afișăm prima pagină
#         products = paginator.page(1)
    
#     # Construim contextul
#     context = {
#         'products': products,
#         'categories': categories,
#         'current_sort': sort_by,
#         'selected_categories': category_ids,
#         'current_price': price_range,
#         'show_in_stock': in_stock == 'true',
#     }
    
#     return render(request, 'core/product_list.html', context)

def product_list(request):
    # Preluăm produsele și alte date necesare
    products_list, sort_by, category_ids, price_range, in_stock = get_filtered_products(request)
    categories = Category.objects.all()
    
    # Creăm un set cu pid-urile produselor din wishlist
    wishlist_products_pids = set()
    if request.user.is_authenticated:
        wishlist_products_pids = set(
            Wishlist.objects.filter(user=request.user)
            .values_list('product__pid', flat=True)
        )
    
    # Marcăm produsele care sunt în wishlist
    for product in products_list:
        product.in_wishlist = product.pid in wishlist_products_pids
    
    # Restul codului pentru paginare etc...
    paginator = Paginator(products_list, 9)
    page = request.GET.get('page', 1)
    
    try:
        products = paginator.page(page)
    except:
        products = paginator.page(1)
    
    context = {
        'products': products,
        'categories': categories,
        'current_sort': sort_by,
        'selected_categories': category_ids,
        'current_price': price_range,
        'show_in_stock': in_stock == 'true',
        'wishlist_products': wishlist_products_pids,  # Adăugăm lista de pid-uri în wishlist
    }
    
    return render(request, 'core/product_list.html', context)

def category_list(request):
    # return HttpResponse('Hello, world!')
    # return HttpResponse('<h1 style="color:red">Hello, world!</h1>')
    cats = Category.objects.all()
    # products = Product.objects.filter(featured=True)

    context = {
        "categories": cats # is the one from above
    }
    return render(request, 'core/categories_list.html', context)
    # return None

def category_detail(request, category_id):
    # Obținem categoria sau returnăm 404 dacă nu există
    # category = get_object_or_404(Category, id=category_id)
    category = get_object_or_404(Category, cid=category_id)
    
    # Preluăm toți furnizorii pentru filtre
    vendors = Furnizor.objects.all()
    
    # Inițializăm query-ul pentru produse cu filtrarea de bază după categorie
    products_list = Product.objects.filter(category=category, status=True)
    
    # Filtrare după preț
    price_range = request.GET.get('price', None)
    if price_range:
        try:
            max_price = float(price_range)
            products_list = products_list.filter(price__lte=max_price)
        except ValueError:
            # Ignorăm dacă prețul nu este un număr valid
            pass
    
    # Filtrare după furnizor (vendor)
    vendor_ids = request.GET.getlist('vendor')
    if vendor_ids:
        vendor_filter = Q()
        for vendor_id in vendor_ids:
            try:
                vendor_filter |= Q(vendor__id=int(vendor_id))
            except ValueError:
                # Ignorăm dacă ID-ul nu este un număr valid
                pass
        products_list = products_list.filter(vendor_filter)
    
    # Filtrare după disponibilitate în stoc
    in_stock = request.GET.get('in_stock')
    if in_stock == 'true':
        products_list = products_list.filter(in_stock=True)
    
    # Sortare
    sort_by = request.GET.get('sort', 'default')
    if sort_by == 'price-low':
        products_list = products_list.order_by('price')
    elif sort_by == 'price-high':
        products_list = products_list.order_by('-price')
    elif sort_by == 'newest':
        products_list = products_list.order_by('-date')
    elif sort_by == 'popular':
        # Presupunem că produsele populare sunt cele marcate ca "featured"
        products_list = products_list.order_by('-featured', 'title')
    
    # Paginare - 9 produse pe pagină
    paginator = Paginator(products_list, 3)
    page = request.GET.get('page', 1)
    
    try:
        products = paginator.page(page)
    except:
        # În caz de erori, afișăm prima pagină
        products = paginator.page(1)
    
    # Construim contextul
    context = {
        'category': category,
        'products': products,
        'vendors': vendors,
        'current_sort': sort_by,
        'selected_vendors': vendor_ids,
        'current_price': price_range,
        'show_in_stock': in_stock == 'true',
    }
    
    return render(request, 'core/category_explore.html', context)

def test_products_view(request):
    all_products = Product.objects.all()
    
    html = """
    <html>
    <head><title>Test Produse</title></head>
    <body>
        <h1>Lista produse în baza de date:</h1>
    """
    
    if all_products.exists():
        html += f"<p>Număr total produse: {all_products.count()}</p><ul>"
        for p in all_products:
            html += f"<li>ID: {p.id}, Titlu: {p.title}, Status: {p.status}, Preț: {p.price}</li>"
        html += "</ul>"
    else:
        html += "<p>Nu există produse în baza de date!</p>"
    
    html += """
    </body>

templates/core/cart.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Coșul meu{% endblock %}

{% block extra_css %}
<style>
  .cart-item {
    border-bottom: 1px solid #eee;
    padding: 15px 0;
  }
  
  .cart-item-image {
    width: 80px;
    height: 80px;
    object-fit: contain;
  }
  
  .qty-control {
    display: flex;
    align-items: center;
  }
  
  .qty-input {
    width: 50px;
    text-align: center;
    border: 1px solid #ddd;
    padding: 5px;
    margin: 0 5px;
  }
  
  .qty-btn {
    background: #f5f5f5;
    border: 1px solid #ddd;
    width: 30px;
    height: 30px;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
  }
  
  .qty-btn:hover {
    background: #eee;
  }
  
  .remove-btn {
    color: #dc3545;
    text-decoration: none;
    font-size: 18px;
  }
  
  .cart-summary {
    background: #f9f9f9;
    padding: 20px;
    border-radius: 5px;
  }
  
  .cart-total-row {
    font-weight: bold;
    border-top: 1px solid #ddd;
    margin-top: 10px;
    padding-top: 10px;
  }
  
  .empty-cart-message {
    text-align: center;
    padding: 50px 0;
    font-size: 18px;
    color: #666;
  }
  
  /* Stiluri pentru notificări */
  .notification {
    position: fixed;
    bottom: 20px;
    right: 20px;
    padding: 15px 20px;
    background-color: #28a745;
    color: white;
    border-radius: 4px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.2);
    opacity: 0;
    transform: translateY(20px);
    transition: all 0.3s ease;
    z-index: 1000;
  }
  
  .notification.error {
    background-color: #dc3545;
  }
  
  .notification.show {
    opacity: 1;
    transform: translateY(0);
  }
  
  /* Responsive */
  @media (max-width: 768px) {
    .cart-item {
      display: flex;
      flex-wrap: wrap;
    }
    
    .cart-item-info {
      width: 100%;
      margin-top: 10px;
    }
  }
</style>
{% endblock %}

{% block content %}
<div class="container py-5">
  <h1 class="mb-4">Coșul meu</h1>
  
  {% csrf_token %}
  
  <div class="row">
    <div class="col-lg-8">
      {% if cart_items %}
        <div class="cart-items-container">
          {% for item in cart_items %}
            <div class="cart-item" data-product-id="{{ item.product.pid }}">
              <div class="row align-items-center">
                <div class="col-md-2 col-4">
                  <img src="{{ item.image }}" alt="{{ item.item }}" class="cart-item-image">
                </div>
                
                <div class="col-md-4 col-8">
                  <h5>{{ item.item }}</h5>
                  <p class="text-muted">{{ item.price }} RON</p>
                </div>
                
                <div class="col-md-3 col-6 mt-3 mt-md-0">
                  <div class="qty-control">
                    <button class="qty-btn" data-product-id="{{ item.product.pid }}" data-action="decrease">-</button>
                    <input type="number" class="qty-input" data-product-id="{{ item.product.pid }}" value="{{ item.qty }}" min="1">
                    <button class="qty-btn" data-product-id="{{ item.product.pid }}" data-action="increase">+</button>
                  </div>
                </div>
                
                <div class="col-md-2 col-4 mt-3 mt-md-0 text-end">
                  <span class="cart-item-subtotal" data-product-id="{{ item.product.pid }}" data-price="{{ item.price }}">
                    {{ item.total }} RON
                  </span>
                </div>
                
                <div class="col-md-1 col-2 mt-3 mt-md-0 text-end">
                  <a href="#" class="remove-from-cart-btn" data-product-id="{{ item.product.pid }}">
                    <i class="fas fa-trash-alt remove-btn"></i>
                  </a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <div class="empty-cart-message">Coșul tău este gol</div>
      {% endif %}
    </div>
    
    <div class="col-lg-4 mt-4 mt-lg-0">
      <div class="cart-summary">
        <h4 class="mb-4">Sumar comandă</h4>
        
        <div class="d-flex justify-content-between mb-2">
          <span>Subtotal:</span>
          <span class="cart-subtotal">{{ subtotal }} RON</span>
        </div>
        
        <div class="d-flex justify-content-between mb-2">
          <span>Livrare:</span>
          <span class="cart-shipping" data-value="{{ shipping }}">{{ shipping }} RON</span>
        </div>
        
        <div class="d-flex justify-content-between cart-total-row">
          <span>Total:</span>
          <span class="cart-total">{{ total }} RON</span>
        </div>
        
        <button class="btn btn-primary w-100 mt-4" {% if not cart_items %}disabled{% endif %}>
          Finalizează comanda
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/cart.js' %}"></script>
{% endblock %}

templates/core/categories_list.html
{% extends 'partials/base.html'  %}
{% load static %}

{% block content %}
<section class="categories-header">
    <div class="container">
        <h1>Categorii de produse</h1>
        <p>Explorează colecția noastră vastă de produse organizate pe categorii</p>
        
        <nav class="breadcrumb">
            <a href="{% url 'core:index' %}">Acasă</a>
            <span class="separator">/</span>
            <span class="current">Categorii</span>
        </nav>
    </div>
</section>

<section class="categories-container">
    <div class="container">
        {% if categories %}
            <div class="categories-grid">
                {% for category in categories %}
                <a href="{% url 'core:category_detail' category.cid %}" class="category-card">
                    <div class="category-image">
                        <img src="{% if category.image %}{{ category.image.url }}{% else %}{% static 'img/placeholder.jpg' %}{% endif %}" alt="{{ category.title }}">
                    </div>
                    <div class="category-content">
                        <h2>{{ category.title }}</h2>
                        <div class="category-overlay">
                            <span class="btn-explore">Explorează</span>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
        {% else %}
            <div class="no-categories">
                <div class="no-categories-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
                </div>
                <h3>Nu există categorii disponibile în acest moment</h3>
                <p>Reveniți mai târziu pentru a vedea colecția noastră de categorii</p>
                <a href="{% url 'core:index' %}" class="back-home">Înapoi la pagina principală</a>
            </div>
        {% endif %}
    </div>
</section>

<style>
    /* Stiluri generale */
    .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 0 20px;
    }

    /* Header secțiune */
    .categories-header {
        background: linear-gradient(135deg, #FFF8E1 0%, #FFECB3 100%);
        padding: 50px 0 30px;
        margin-bottom: 40px;
    }

    .categories-header h1 {
        font-size: 36px;
        color: #e55b00;
        margin-bottom: 10px;
        font-weight: 700;
    }

    .categories-header p {
        font-size: 18px;
        color: #666;
        max-width: 600px;
        margin: 0 auto 20px;
    }
    
    .breadcrumb {
        margin-bottom: 15px;
        color: #777;
        font-size: 14px;
    }
    
    .breadcrumb a {
        color: #555;
        text-decoration: none;
    }
    
    .breadcrumb a:hover {
        color: #e55b00;
    }
    
    .breadcrumb .separator {
        margin: 0 8px;
    }
    
    .breadcrumb .current {
        color: #e55b00;
        font-weight: 500;
    }

    /* Grid pentru categorii */
    .categories-grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 30px;
        margin-bottom: 60px;
    }

    /* Card categorie */
    .category-card {
        display: block;
        text-decoration: none;
        background-color: #fff;
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 8px 20px rgba(0,0,0,0.1);
        transition: all 0.3s ease;
        height: 100%;
    }

    .category-card:hover {
        transform: translateY(-10px);
        box-shadow: 0 15px 30px rgba(0,0,0,0.15);
    }

    .category-image {
        height: 220px;
        overflow: hidden;
        position: relative;
    }

    .category-image img {
        width: 100%;
        height: 100%;
        object-fit: cover;
        transition: transform 0.5s ease;
    }

    .category-card:hover .category-image img {
        transform: scale(1.1);
    }

    .category-content {
        padding: 20px;
        position: relative;
        text-align: center;
    }

    .category-content h2 {
        font-size: 22px;
        color: #333;
        margin: 0;
        transition: color 0.3s ease;
    }

    .category-card:hover .category-content h2 {
        color: #e55b00;
    }

    .category-overlay {
        position: absolute;
        bottom: -50px;
        left: 0;
        right: 0;
        text-align: center;
        transition: bottom 0.3s ease, opacity 0.3s ease;
        opacity: 0;
    }

    .category-card:hover .category-overlay {
        bottom: 20px;
        opacity: 1;
    }

    .btn-explore {
        display: inline-block;
        background-color: #e55b00;
        color: white;
        padding: 10px 20px;
        border-radius: 25px;
        font-weight: 500;
        box-shadow: 0 4px 10px rgba(229, 91, 0, 0.3);
        transition: background-color 0.3s ease;
    }

    .btn-explore:hover {
        background-color: #333;
    }

    /* Stil pentru nicio categorie */
    .no-categories {
        text-align: center;
        padding: 60px 0;
        background-color: #f9f9f9;
        border-radius: 12px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.05);
    }

    .no-categories-icon {
        margin-bottom: 20px;
        color: #aaa;
    }

    .no-categories h3 {
        font-size: 24px;
        color: #555;
        margin-bottom: 15px;
    }

    .no-categories p {
        color: #888;
        max-width: 500px;
        margin: 0 auto 20px;
    }
    
    .back-home {
        display: inline-block;
        background-color: #e55b00;
        color: white;
        text-decoration: none;
        padding: 10px 20px;
        border-radius: 25px;
        transition: background-color 0.2s;
    }
    
    .back-home:hover {
        background-color: #d45400;
    }

    /* Responsive design */
    @media (max-width: 992px) {
        .categories-grid {
            grid-template-columns: repeat(2, 1fr);
        }
        
        .categories-header {
            padding: 40px 0 25px;
        }
        
        .categories-header h1 {
            font-size: 30px;
        }
    }

    @media (max-width: 576px) {
        .categories-grid {
            grid-template-columns: 1fr;
        }
        
        .category-image {
            height: 180px;
        }
        
        .categories-header h1 {
            font-size: 24px;
        }
        
        .categories-header p {
            font-size: 16px;
        }
    }
</style>
{% endblock content %}