core/urls.py
from django.urls import path
from core.views import index, test_products_view, home_view, product_list, category_list, category_detail, cart_action, get_cart_items, get_cart_count, cart_view
from core import views

app_name = "core"

urlpatterns = [
    # path("ceva/", views.index), 
    path("", index, name="index"),

    path("products", product_list, name="product-list"),

    path("categories", category_list, name="category-list"),
    path("categories", category_list, name="categories"),  # Adaugă acest URL cu numele "categories"
    path('category/<str:category_id>/', views.category_detail, name='category_detail'),

    path('wishlist/toggle/', views.toggle_wishlist, name='toggle-wishlist'),
    path('wishlist/', views.get_wishlist, name='get-wishlist'), 

    path('cart/items/', get_cart_items, name='get_cart_items'),
    path('cart/count/', get_cart_count, name='get_cart_count'),
    path('cart/', cart_view, name='cart_view'),
    path('cart/action/', cart_action, name='cart_action'),

    path("aaaa/", test_products_view, name='test_products'),
    path("aaa/", home_view, name='home'),
    # Here I'm telling it where to put that =)) beaware of the paths!
]

proiect/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings # it accesses settings.py from upper
from django.conf.urls.static import static

from core.views import index, category_detail, category_list, cart_action, cart_view, get_cart_count, get_cart_items
urlpatterns = [
    path('admin/', admin.site.urls),
    # path("", index)
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),    
    path('', include('core.urls')),
    path('', index, name='index'),
    path('categories/', category_list, name='category_list'),  # Verifică acest nume
    path('category/<str:category_id>/', category_detail, name='category_detail'),
     path('cart/action/', cart_action, name='cart_action'),
    path('cart/items/', get_cart_items, name='get_cart_items'),
    path('cart/count/', get_cart_count, name='get_cart_count'),
    path('cart/', cart_view, name='cart_view'),

]

# all thr static files are stored in teh static directory in root directory

if settings.DEBUG:     
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
# class User(models.Model): # Inheritance
class User(AbstractUser): # Inheritance
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email
    

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User
# if you open up the libs you can customize thiungs around there

class UserRegisterForm(UserCreationForm):
# class UserRegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Nume de utilizator"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"e-mail"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Parola..."}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirmare parola"}))
    class Meta:
        model = User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm # , LoginForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from userauths.models import User
# from django.contrib.auth import logout
# from .forms import LoginForm

# User = settings.AUTH_USER_MODEL # userauths.user -> the model we made

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid(): # the token thing
            new_user = form.save() # it creates new user ig
            username = form.cleaned_data.get("username")
            # email = form.cleaned_data.get("email")
            messages.success(request, f"Adaugare cu succes utilizator {username}")
            new_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password1'])
            login(request, new_user)
            print("Inregistrare realizata cu succes")
            return redirect("core:index")
    else:
        print("Nu se poate face inregistrarea")
        form = UserRegisterForm()

    context = {
        # "ceva" : form
        "form" : form
    }
    return render(request, "userauths/sign-up.html", context)

def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Utilizator deja conectat!")
        return redirect("core:index")
    
    if request.method == "POST":
        # form = LoginForm(request.POST)
        # if form.is_valid():
        email = request.POST.get("email") # the email passed in
        password = request.POST.get("password")
        try:
            # user = User.objects.all() # when you want to take all attributes?
            user = User.objects.get(email=email) # just one attribute -> the email attribute equals the email extracted from thr form
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Utilizator conectat cu succes!")
                return redirect("core:index")
            else:
                messages.warning(request, "Utilizator negasit")

        except:
            messages.warning(request, f"Nu exista utilizatorul cu email-ul {email}")
        # else:
        #     form = LoginForm()
    #         context = {
    #             # "form": form
    #             "email": email,
    #             "password": password
    #         }
    #         # return redirect(request, "userauths/sign-in.html", context)
    #         return render(request, "userauths/sign-in.html", context)
    # else:
        # return render(request, "userauths/sign-in.html")
    return render(request, "userauths/sign-in.html")

def logout_view(request):
    logout(request)
    messages.success(request, f"Deconectare cu succes!")
    # Verificăm care e numele corect în urls.py pentru view-ul de login
    # Este posibil să fie 'login' sau 'signin' în loc de 'sign-in'
    return redirect("userauths:sign-in")

templates/userauths/sign-in.html

{% load static %}

<!-- <form action="">
    <input type="text" placeholder="e-mail...">
    <input type="text" placeholder="username...">
    <input type="password" placeholder="password...">
    <input type="password" placeholder="confirm password">
    <button>Inregistare</button>
</form> -->

<!-- {{form}} -->
<!-- <form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Inregistrare</button>
</form> -->
<!-- {% if form.errors %}
<div class="alert alert-danger">
    <strong>{{ form.errors }}</strong>
</div>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    <div class = "form-group">
        {{form.username}}
    </div>
    <div class = "form-group">
        {{form.email}}
    </div>
    <div class = "form-group">
        {{form.password1}}
    </div>
    <div class = "form-group">
        {{form.password2}}
    </div>
    <button type="submit">Inregistrare</button>
</form> -->
<!-- <textarea name="" id="" cols="30" rows="10"></textarea> -->

<html lang="ro">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Conectare</title>
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
</head>

<section class="register">
    <h2>Conectare</h2>

    {% if form.errors %}
    <div class="alert alert-danger">
        <strong>{{ form.errors }}</strong>
    </div>
    {% endif %}
    {% if messages %}
        {%  for i in messages %}
            <div class="alert alert-{{i.tags}}"><strong>{{i}}</strong></div>
        {% endfor %}
    {% endif %}
    <p>Nu aveti cont?<br> Nu e panica! <br><strong><a href="{% url 'userauths:sign-up' %}"> Inscrieti-va!</a></strong></p>
    <form action="" method="POST">
        {% csrf_token %}

        <!-- <div class="form-group">
            <label for="id_email">E-mail</label>
            {{ form.email }}
        </div>

        <div class="form-group">
            <label for="id_password1">Parolă</label>
            {{ form.password }}
        </div> -->

        <!--  We have to build it from scracth this time -->

        <div class="form-group">
            <label for="id_username">Nume de utilizator/e-mail</label>
            <input id="username" type="text" required name="email" placeholder="Nume de utilizator sau email">
        </div>

        <div class="form-group">
            <label for="id_password">Parolă</label>
            <input type="password" required name="password" placeholder="Parola">
        </div>

        <button type="submit" class="btn">Conectare</button>
    </form>
</section>
<!-- <script src="https:://code.jquery.com/jquery-3.5.1.min.js"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    setTimeout(() => {
        $(".alert").fadeOut(500, function() {
            $(this).remove();
        });
    }, 3000);
</script>

templates/userauths/sign-up.html

{% load static %}

<!-- <form action="">
    <input type="text" placeholder="e-mail...">
    <input type="text" placeholder="username...">
    <input type="password" placeholder="password...">
    <input type="password" placeholder="confirm password">
    <button>Inregistare</button>
</form> -->

<!-- {{form}} -->
<!-- <form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Inregistrare</button>
</form> -->
<!-- {% if form.errors %}
<div class="alert alert-danger">
    <strong>{{ form.errors }}</strong>
</div>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    <div class = "form-group">
        {{form.username}}
    </div>
    <div class = "form-group">
        {{form.email}}
    </div>
    <div class = "form-group">
        {{form.password1}}
    </div>
    <div class = "form-group">
        {{form.password2}}
    </div>
    <button type="submit">Inregistrare</button>
</form> -->
<!-- <textarea name="" id="" cols="30" rows="10"></textarea> -->

<html lang="ro">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Înregistrare</title>
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
</head>

<section class="register">
    <h2>Înregistrare</h2>

    {% if form.errors %}
    <div class="alert alert-danger">
        <strong>{{ form.errors }}</strong>
    </div>
    {% endif %}
    {% if messages %}
        {%  for i in messages %}
            <div class="alert alert-{{i.tags}}"><strong>{{i}}</strong></div>
        {% endfor %}
    {% endif %}
    <p>Aveti deja cont?<br> Foarte bine! <br><strong><a href="{% url 'userauths:sign-in' %}">Conectati-va!</a></strong></p>
    <form action="" method="POST">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_username">Nume de utilizator</label>
            {{ form.username }}
        </div>

        <div class="form-group">
            <label for="id_email">E-mail</label>
            {{ form.email }}
        </div>

        <div class="form-group">
            <label for="id_password1">Parolă</label>
            {{ form.password1 }}
        </div>

        <div class="form-group">
            <label for="id_password2">Confirmare parolă</label>
            {{ form.password2 }}
        </div>

        <button type="submit" class="btn">Înregistrare</button>
    </form>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<!-- <script src="https:://code.jquery.com/jquery-3.5.1.min.js"></script> -->
<script>
    setTimeout(() => {
        $(".alert").fadeOut(500, function() {
            $(this).remove();
        });
    }, 3000);
</script>